# Naeemah Davis
# Register Screen
from tkinter import *

register = Tk()
register.geometry("800x900")
register.config(bg="#EBFFEC")
register.resizable(width=False, height=False)
register.title("Life Choices Online")

lbl_title = Label(register, text="Life Choices Online", fg="#71D696", bg="#EBFFEC", font="Purisa 40 bold")
lbl_title.place(x=110,y=20)
lbl_register = Label(register, text="Registration", fg="#71D696", bg="#EBFFEC", font="Purisa 30 bold")
lbl_register.place(x=250, y=100)
lbl_details = Label(register, text="Personal Details", fg="#206F3D", bg="#EBFFEC", font="Poppins 20")
lbl_details.place(x=250, y=190)
lbl_name = Label(register, text="Name:", fg="#206F3D", bg="#EBFFEC", font="Poppins 18")
lbl_name.place(x=250, y=240)
e_name = Entry(register, fg="#206F3D", bg="#EBFFEC", font="Poppins 18")
e_name.place(x=250, y=270)
lbl_surname = Label(register, text="Surname:", fg="#206F3D", bg="#EBFFEC", font="Poppins 18")
lbl_surname.place(x=250, y=320)
e_surname = Entry(register, fg="#206F3D", bg="#EBFFEC", font="Poppins 18")
e_surname.place(x=250, y=350)
lbl_idNo = Label(register, text="ID Number:", fg="#206F3D", bg="#EBFFEC", font="Poppins 18")
lbl_idNo.place(x=250, y=400)
e_id = Entry(register, fg="#206F3D", bg="#EBFFEC", font="Poppins 18")
e_id.place(x=250, y=430)
lbl_contactNo = Label(register, text="Contact No:", fg="#206F3D", bg="#EBFFEC", font="Poppins 18")
lbl_contactNo.place(x=250, y=480)
e_contact = Entry(register, fg="#206F3D", bg="#EBFFEC", font="Poppins 18")
e_contact.place(x=250, y=510)
lbl_nextOK = Label(register, text="Next of Kin Details", fg="#206F3D", bg="#EBFFEC", font="Poppins 20")
lbl_nextOK.place(x=250, y=570)
lbl_nextOKname = Label(register, text="Name:", fg="#206F3D", bg="#EBFFEC", font="Poppins 18")
lbl_nextOKname.place(x=250, y=620)
e_nextOK_name = Entry(register, fg="#206F3D", bg="#EBFFEC", font="Poppins 18")
e_nextOK_name.place(x=250, y=650)
lbl_nextOK_contactNo = Label(register, text="Contact No:", fg="#206F3D", bg="#EBFFEC", font="Poppins 18")
lbl_nextOK_contactNo.place(x=250, y=700)
e_nextOK_contactNo = Entry(register, fg="#206F3D", bg="#EBFFEC", font="Poppins 18")
e_nextOK_contactNo.place(x=250, y=730)
btn_back = Button(register, text="Back", bg="grey", fg="#EBFFEC", font="Arial 25 bold")
btn_back.place(x=60, y=820)
btn_clear = Button(register, text="Clear", bg="grey", fg="#EBFFEC", font="Arial 25 bold")
btn_clear.place(x=600, y=720, width=120)
btn_submit = Button(register, text="SUBMIT", fg="#206F3D", bg="#71D696", font="Arial 25 bold")
btn_submit.place(x=300, y=820)
btn_exit = Button(register, text="Exit", bg="grey", fg="#EBFFEC", font="Arial 25 bold")
btn_exit.place(x=600, y=820, width=120)
register.mainloop()